### ISSUE TITLE
Could you update it to fit newest openwrt

### ISSUE THREAD

**Issue by jack338c** [presisco/openwrt-irq-balance#3]
please have a look,I build newest openwrt master from offical and get a lot of error log from my ea7500 v1 with your script ,thanks

root@Openwrt:/etc/init.d# /etc/init.d/set_smp_affinity restart
using cpu: 0 1 for network queues
binding cpu for eth0 queues
binding cpu for eth0.2 queues
sh: write error: No such file or directory
binding cpu for eth1 queues
binding cpu for eth1.1 queues
sh: write error: No such file or directory
binding cpu for wlan0 queues
sh: write error: No such file or directory
binding cpu for wlan1 queues
sh: write error: No such file or directory
enabling offload on eth0
enabling offload on eth0.2
enabling offload on eth1
enabling offload on eth1.1
net.core.rps_sock_flow_entries = 8192
set mask 1 for irq: 39
set mask 1 for irq: 40
set mask 1 for irq: 41
set mask 1 for irq: 37
set mask 1 for irq: 38
set mask 1 for irq: 50
set mask 1 for irq: 51

**Comment by presisco** [comment]
master is unstable, i'll test the script when stable 21.02 release

**Comment by jack338c** [comment]
ok ,thank you
